write_small <- function(res, filename, cols=list()){
  cols <- c(cols,
            c("t" , "sim",
#              "Rt",
              "beta_dyn_change",
              "beta_cp",
              "tot_infected", "hosp", "tot_hosp", "beta_thresh",
              "tot_infected_1",
              "tot_infected_2",
              "tot_infected_3",
              "tot_infected_4",
              "tot_infected_5",
              "tot_infected_6",
              "tot_infected_7",
              "tot_infected_8",
              "tot_infected_9",
              "D_1",
              "D_2",
              "D_3",
              "D_4",
              "D_5",
              "D_6",
              "D_7",
              "D_8",
              "D_9",
              "tot_hosp_1",
              "tot_hosp_2",
              "tot_hosp_3",
              "tot_hosp_4",
              "tot_hosp_5",
              "tot_hosp_6",
              "tot_hosp_7",
              "tot_hosp_8",
              "tot_hosp_9",
              "tot_resp_1",
              "tot_resp_2",
              "tot_resp_3",
              "tot_resp_4",
              "tot_resp_5",
              "tot_resp_6",
              "tot_resp_7",
              "tot_resp_8",
              "tot_resp_9",
              "resp",
              "incidence", "hosp_incidence", "tot_resp"))
  saveRDS(res[, ..cols], filename)

}

